minimumReleaseAge: 10080
trustPolicy: no-downgrade

allowBuilds:
  '@prisma/engines': set this to true or false
  core-js: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
